/*
 * Copyright 2011 Free Software Foundation, Inc.
 *
 * This file was generated by gr_modtool, a tool from the GNU Radio framework
 * This file is a part of gr-fec_dev
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

#ifndef INCLUDED_FEC_DEV_API_H
#define INCLUDED_FEC_DEV_API_H

#include <gnuradio/attributes.h>

#ifdef gnuradio_fec_dev_EXPORTS
#define FEC_DEV_API __GR_ATTR_EXPORT
#else
#define FEC_DEV_API __GR_ATTR_IMPORT
#endif

#endif /* INCLUDED_FEC_DEV_API_H */
